Update PhpDateTimeParser for PHP 8.1
wmde/Time pull request #162
Opened 2022-10-18 20:32 UTC by mariushoch

Starting from PHP 8.1 `DateTime` interprets `YYYY-DDD` as the DDDth day of the year.

We need to take this into account (to not accidentally mangle input into that format).

2022-10-18 20:47 UTC, mariushoch commented
For other reasons CI is still broken on PHP 8.1 :/

2022-10-19 08:28 UTC, lucaswerkmeister commented
I don’t understand this change yet… do we want to support YYYY-MMM dates (why?), and this is needed to get it working?

It also doesn’t work on my system (PHP 8.1.2):
```
1) ValueParsers\Test\PhpDateTimeParserTest::testParseWithValidInputs with data set #76 ('2022-033', DataValues\TimeValue Object (...))
ValueParsers\ParseException: Failed to parse time string (2022-033) at position 7 (3): Unexpected character

/var/www/html/wiki1/vendor/data-values/time/src/ValueParsers/PhpDateTimeParser.php:114
/var/www/html/wiki1/vendor/data-values/time/vendor/data-values/common/src/ValueParsers/StringValueParser.php:47
/var/www/html/wiki1/vendor/data-values/time/tests/ValueParsers/ValueParserTestCase.php:67
```

```
php > echo phpversion(); new DateTime('2022-033');
8.1.2
PHP Warning:  Uncaught Exception: Failed to parse time string (2022-033) at position 7 (3): Unexpected character in php shell code:1
Stack trace:
#0 php shell code(1): DateTime->__construct()
#1 {main}
  thrown in php shell code on line 1
```

2022-10-20 21:11 UTC, mariushoch commented
Well, the problem is that our conversion code (see `PhpDateTimeParser::getValueWithFixedSeparators`) mangled dates like "0111 111 111" into "0111-111-111" which `DateTime` suddenly started to "understand".

Apparently this behavior was only changed in [PHP 8.1.7](https://bugs.php.net/bug.php?id=51987).

2022-10-21 09:26 UTC, lucaswerkmeister commented
Okay, I see – without this change, on PHP 8.1.11, one of the test fails:

```
1) ValueParsers\Test\PhpDateTimeParserTest::testParseWithInvalidInputs with data set #7 ('111 111 111')
Failed asserting that exception of type "ValueParsers\ParseException" is thrown.

FAILURES!
Tests: 760, Assertions: 861, Failures: 1.
```

And this test is untouched by this PR, so the PR correctly makes this input invalid again. Makes sense.

2022-10-21 09:26 UTC, lucaswerkmeister requested changes
LGTM otherwise

2022-10-21 09:26 UTC, lucaswerkmeister commented on src/ValueParsers/PhpDateTimeParser.php
> +		// Since PHP 8.1 YYYY-DDD means the DDDth day of the year, thus only add dashes
Can you change this to 8.1.7 as well?

2022-10-21 09:45 UTC, lucaswerkmeister approved these changes

2022-10-21 09:50 UTC, lucaswerkmeister commented
Also tested manually (since we don’t test PHP 8.1 in CI yet).

2022-10-21 09:53 UTC, merged